fix: now pot only applied to WebEmbedded
lavalink-devs/youtube-source pull request #47
Opened 2024-09-11 16:29 UTC by KagChi

WARNING!!!! THIS PR INCLUDES MAJOR BREAKING CHANGES TO LAVAPLAYER USERS.

Enjoy the fix. here is the snapshot plugin http://cdn.sazumi.moe/f/sv-53Nvn.jar

2024-09-11 16:31 UTC, devoxin requested changes

2024-09-11 16:31 UTC, devoxin commented on common/src/main/java/dev/lavalink/youtube/clients/skeleton/NonMusicClient.java
> +        if (config.getName() == "WEB_EMBEDDED_PLAYER" || status == null) {
This isn't how string equality checking works in Java.

2024-09-11 16:31 UTC, devoxin commented
Please state your reasoning for this PR.

2024-09-11 16:35 UTC, KagChi commented
> Please state your reasoning for this PR and what this aims to fix.

YouTube seems to be block poToken workaround on Web client. passing it to WebEmbedded fixes the issue.

2024-09-11 16:37 UTC, devoxin commented
Block how? Do requests fail outright with `pot` specified compared to not? Or does it now make no difference whether `pot` is supplied?

To avoid a breaking change I would at least keep the method in the `Web` client. Either no-op it if it breaks any and all requests with it supplied, or keep it as-is if it makes no difference regardless.

2024-09-11 16:39 UTC, devoxin commented
Also perhaps embedded clients should expose a flag determining whether they're embedded, so that the appropriate embed client configuration can be applied. Something like
```java
if (status == null || client.isEmbedded()) {
  config.withClientField("clientScreen", "EMBED")
    .withThirdPartyEmbedUrl("https://google.com");
}
```

2024-09-11 16:40 UTC, Nansess commented
> Block how? Do requests fail outright with `pot` specified compared to not? Or does it now make no difference whether `pot` is supplied?
> 
> To avoid a breaking change I would at least keep the method in the `Web` client. Either no-op it if it breaks any and all requests with it supplied, or keep it as-is if it makes no difference regardless.

certain flagged IPs when used with PoTokens will result in "please sign in" this seems to be only for the WEB client and doesn't effect WebEmbed

2024-09-16 14:27 UTC, KagChi commented
Any updates on this @devoxin ?

2024-09-16 17:43 UTC, devoxin approved these changes

2024-09-16 17:43 UTC, merged